---

- name: Generate htpasswd
  hosts: host
  remote_user: "{{ docker_user }}"

  tasks:
    - htpasswd: >
        path="{{ proxy_path }}/proxy/passwords/{{ domain }}"
        name="{{ user }}"
        password="{{ pass }}"
      when: domain is defined and user is defined and pass is defined
